CREATE DATABASE IF NOT EXISTS pelindo_crypto;
USE pelindo_crypto;

CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    signature_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS keys_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_type VARCHAR(50) DEFAULT 'ECC-SECP256K1',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
